version: '3.0'
services:
  web:
    container_name: gostudybe
    image: psh3253/gostudybe:1.0
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    image: psh3253/nginx:1.0
    ports:
      - "80:80"